USE master
GO

IF (EXISTS(SELECT * FROM sys.databases WHERE NAME = 'ExemploSenai'))
DROP DATABASE ExemploSenai
GO

CREATE DATABASE ExemploSenai
GO

USE ExemploSenai
GO

CREATE TABLE Usuario(
ID INT IDENTITY PRIMARY KEY,
Nome VARCHAR(200) NOT NULL,
Senha VARCHAR(1000) NOT NULL,
);
GO

CREATE TABLE Post(
ID INT IDENTITY PRIMARY KEY,
Publicador INT REFERENCES Usuario(ID),
Conteudo VARCHAR(MAX) NOT NULL,
Momento DATETIME NOT NULL
);
GO
